/*
  Licence: GPLv2 or later
  Copyright Ⓒ 2026 Jordan Haisley
  draft/oper

*/
/*** <<<MODULE MANAGER START>>>
module
{
		documentation "https://github.com/jhaisley/unrealircd-mods/blob/main/oper-tag/README.md";
		troubleshooting "In case of problems, please file a bug report at https://github.com/jhaisley/unrealircd-mods/issues/new";
		min-unrealircd-version "6.*";
		max-unrealircd-version "6.*";
		post-install-text {
				"The module is installed. Now all you need to do is add a loadmodule line:";
				"loadmodule \"third/oper-tag\";";
				"And /REHASH the IRCd.";
				"The module does not need any other configuration.";
				"Please note that the implemented feature is still \"Work In Progress\".";
		}
}
*** <<<MODULE MANAGER END>>>
*/

#include "unrealircd.h"

/* The spec is a work in progress, so the prefixed names must be used.
 * See: https://ircv3.net/specs/extensions/oper-tag
 */
#define MTAG_OPER "draft/oper"
#define CAP_NAME_OPER_TAG "draft/oper-tag"

ModuleHeader MOD_HEADER = {
	"third/oper-tag",
	"1.0",
	"draft/oper tag - Marks messages that originate from an IRC operator",
	"Jordan Haisley",
	"unrealircd-6",
};

/* Global variables */
long CAP_OPER_TAG = 0L;

/* Forward declarations */
int opertag_mtag_is_ok(Client *client, const char *name, const char *value);
void mtag_add_opertag(Client *client, MessageTag *recv_mtags, MessageTag **mtag_list, const char *signature);

MOD_INIT()
{
	ClientCapabilityInfo cap;
	ClientCapability *c;
	MessageTagHandlerInfo mtag;

	MARK_AS_GLOBAL_MODULE(modinfo);

	memset(&cap, 0, sizeof(cap));
	cap.name = CAP_NAME_OPER_TAG;
	c = ClientCapabilityAdd(modinfo->handle, &cap, &CAP_OPER_TAG);

	memset(&mtag, 0, sizeof(mtag));
	mtag.name = MTAG_OPER;
	mtag.is_ok = opertag_mtag_is_ok;
	mtag.clicap_handler = c;
	MessageTagHandlerAdd(modinfo->handle, &mtag);

	HookAddVoid(modinfo->handle, HOOKTYPE_NEW_MESSAGE, 0, mtag_add_opertag);

	return MOD_SUCCESS;
}

MOD_LOAD()
{
	return MOD_SUCCESS;
}

MOD_UNLOAD()
{
	return MOD_SUCCESS;
}

/** This function verifies if the client sending the mtag is permitted to do so.
 * The tag is generated by the server, so only servers may relay it. A value is
 * always rejected: this module never discloses the operator identity, so a
 * linked server cannot inject one through the tag either.
 */
int opertag_mtag_is_ok(Client *client, const char *name, const char *value)
{
	if (IsServer(client) && (value == NULL))
		return 1; /* OK */

	return 0;
}

void mtag_add_opertag(Client *client, MessageTag *recv_mtags, MessageTag **mtag_list, const char *signature)
{
	MessageTag *m;

	/* Users with +H asked for their oper status to be hidden. The outgoing
	 * filter only sees the recipient, never the sender, so the tag cannot be
	 * limited to opers alone -- it is left off entirely rather than leaking.
	 */
	if (IsUser(client) && IsOper(client) && !IsHideOper(client))
	{
		m = safe_alloc(sizeof(MessageTag));
		safe_strdup(m->name, MTAG_OPER);
		m->value = NULL;
		AddListItem(m, *mtag_list);
	}
}
